### ISSUE TITLE
Migration plan: Checklist

### ISSUE THREAD

**Issue by anggxyz** [anggxyz/convo-app#65]
- [ ] write a script to move data from digitalocean DB to supabase (do we need to pay for Supabase?)
- [ ] setup a sync conversation with the stewards (v,a,a,s) to review:
    - [ ] functionality
        - [ ] create an event: everyone creates an event (2 create series, 2 single events)
        - [ ] view the events on google calendar + slack (test channel)
        - [ ] rsvp: everyone rsvps to 3 events (2 anonymously, 1 with email)
        - [ ] should receive email invite for 1 
        - [ ] edit rsvp for 1 anonymously rsvp'd event - add email, receive invite
        - [ ] edit proposed event (will later be adding a filter option on `/all` to be able to filter for just owned events)
    - [ ] copy of all pages
    - [ ] look and feel (UI)
- [ ] move domains (convo.kernel -> cloudflare, i should have access via angela@kernel)
- [ ] post a lowkey announcement on #kernel-convo or #announcements?

**Comment by anggxyz** [comment]
### Migration Plan
- remove test events from `convo.cafe` (supabase)
- use `http://159.89.164.29/getAllEvents` -- export all events in a json
- place json in `/src/server/scripts/migrateToV2.json`
- place script in `/src/server/scripts/migrateToV2.ts`
- use Database URL to directly interact with the DB (not sure if vercel has a way to run a script)
- create event in the database with the following changes (check if `hash` already exists, skip if yes)
  - mark `isImported` = true
  - let RSVPs[] be empty (we can't accurately import all the RSVP data, and i think that should be okay)
  - fetch all rsvp emails and store in `emails[]`
  - for proposer, create a new entry (**upsert**) in `user`
    - address: email address
    - nickname: nickname
- any UI changes?
